'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CC_JO.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE DB_A3F994_co
        '''IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        '''begin
        '''EXEC [DB_A3F994_co].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        '''end
        '''GO
        '''
        '''CREATE TABLE [dbo].[AppInfo](
        '''    [Property] [nvarchar](100) NOT NULL,
        '''    [Value] [nvarchar](100) NULL
        ''') ON [PRIMARY]
        '''GO
        '''
        '''SET ANSI_NULLS ON
        '''GO
        '''SET QUOTED_IDENTIFIER ON
        '''GO
        ''' 
        '''INSERT [dbo].[AppInfo] ([Property], [Value]) VALUES (N&apos;Version&apos;, N&apos;1.0.0.1&apos;)
        '''.
        '''</summary>
        Friend Shared ReadOnly Property CREATE_TABLE_AppInfo() As String
            Get
                Return ResourceManager.GetString("CREATE_TABLE_AppInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [master]
        '''GO
        '''/****** Object:  Database [DB_A3F994_co]    Script Date: 24/09/2021 01:51:11 م ******/
        '''CREATE DATABASE [DB_A3F994_co] ON  PRIMARY 
        '''( NAME = N&apos;DB_A3F994_co&apos;, FILENAME = N&apos;E:\dbsql\2017\DB_A3F994_CC_JO.mdf&apos; , SIZE = 75520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        ''' LOG ON 
        '''( NAME = N&apos;DB_A3F994_co_log&apos;, FILENAME = N&apos;E:\dbsql\2017\DB_A3F994_co_log.ldf&apos; , SIZE = 259776KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
        '''GO
        '''ALTER DATABASE [DB_A3F994_co] SET COMPATIBILITY_LEVEL = 100
        '''GO
        '''IF (1 =  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property CreateClientDataBase() As String
            Get
                Return ResourceManager.GetString("CreateClientDataBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE DB_A3F994_co
        '''GO
        '''ALTER TABLE AddMail
        '''ADD Email Nvarchar(100)  
        '''GO
        '''UPDATE AppInfo set Value=&apos;1.0.0.3&apos; where 
        '''Property=&apos;Version&apos; .
        '''</summary>
        Friend Shared ReadOnly Property UpdateDB_CO() As String
            Get
                Return ResourceManager.GetString("UpdateDB_CO", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
